# 預提交鉤子配置
# 安裝: pre-commit install

repos:
  # Python 代碼格式化
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Import 排序
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # 代碼風格檢查
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        additional_dependencies: [flake8-docstrings]

  # 類型檢查
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-PyYAML, types-requests]

  # 安全檢查
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--skip, B101, --exclude, tests]

  # 基本檢查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # 移除行尾空白
      - id: trailing-whitespace
      # 確保檔案以換行符結束
      - id: end-of-file-fixer
      # 檢查YAML格式
      - id: check-yaml
        args: [--allow-multiple-documents]
      # 檢查JSON格式
      - id: check-json
      # 檢查合併衝突標記
      - id: check-merge-conflict
      # 檢查大檔案
      - id: check-added-large-files
        args: [--maxkb=1000]
      # 檢查Python語法
      - id: check-ast
      # 檢查Python字節碼檔案
      - id: check-byte-order-marker
      # 檢查檔案名稱
      - id: check-case-conflict
      # 混合行結束符檢查
      - id: mixed-line-ending
        args: [--fix=lf]

  # Docker檔案檢查
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]

  # Shell腳本檢查
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  # 密鑰檢查
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: |
          (?x)^(
              .*\.lock$|
              .*\.min\.js$|
              .*\.min\.css$
          )$

# 全域排除
exclude: |
  (?x)^(
      venv/.*|
      \.venv/.*|
      data/.*|
      logs/.*|
      htmlcov/.*|
      \.git/.*|
      \.pytest_cache/.*|
      __pycache__/.*|
      .*\.pyc$|
      .*\.pyo$|
      .*\.egg-info/.*
  )$